# Use root/example as user/password credentials
version: '3'

services:

  db:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: openlist
    network_mode: bridge
      
      

  openlist:
    image: nicklewanowicz/openlist-backend
    depends_on:
    - db
    restart: always
    ports:
      - 8000:8080
    network_mode: bridge
