# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  openlist:
    image: myapp
    restart: always
    ports:
      - 8000:8000